
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dronesDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false #DEBUG only
    generate-ddl: false
    hibernate:
      ddl-auto: validate
