#
#server.port=8090
#drone.service.url=http://droneService/audit
#eureka.instance.hostname=localhost
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#
#cron-expression=*/10 * * * * ?
#spring.data.mongodb.uri=mongodb://localhost:27017/EmployeeDB
#spring:
#  datasource:
#    url: jdbc:mongodb://localhost:27017/EmployeeDB
#
#    driver-class-name: org.spring.mongo.demo
#  jpa:
#    show-sql: false #DEBUG only
#    generate-ddl: false
#    hibernate:
#      ddl-auto: update
#spring.data.mongodb.uri=mongodb://localhost:27017/droneDB
#service discovery
server:
  port: 8090
eureka:
  instance:
    hostname: localhost
  client:
    service-url.defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  mongodb:
    embedded:
      version: DEVELOPMENT
  data:
    mongodb:
      host: localhost
      port: 27017
      database: droneLog

  application:
    name: monitoringService
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    kubernetes:
      config:
        enabled: false
      discovery:
        enabled: false
    discovery:
      client:
        composite-indicator:
          enabled: false
ribbon:
  eureka:
    enabled: false
  ReadTimeout: 60000
  ConnectionTimeout: 60000



drone:
  logPeriod: 30000 #every 30 sec
  statePeriod: 60000
