


eureka:
  instance:
    hostname: localhost
  client:
    service-url.defaultZone: http://localhost:8761/eureka/

server:
  port: 8079


#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: droneService
          uri: http://localhost:8080/
          predicates:
            - Path= /drones-service/**
          filters:
            - RewritePath=/drones-service/(?<path>.*), /$\{path}
        - id: monitoringService
          uri: http://localhost:8090/
          predicates:
            - Path= /monitoring-service/**
          filters:
            - RewritePath=/monitoring-service/(?<path>.*), /$\{path}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'
